/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3dcbe86d-6273-459b-ba6a-068d2e4b2e3c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Ay72Lbt6a",
    "aws_user_pools_web_client_id": "7kc84dod19bhtoufqc2o40kptn",
    "oauth": {
        "domain": "pineconee519da81-e519da81-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/",
        "redirectSignOut": "http://localhost:4200/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://nsgbba532re57pmty6n7gzqzha.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
